export default {
	"pages": {
		"root": {
			"id": "root",
			"pageUrl": "root",
			"name": "root",
			"children": [
				"68d745af90a2bb0024b90422",
				"68d745af90a2bb0024b90425",
				"68d745ed4cbc690025c0c304",
				"68daa3add788530023e0c839",
				"68daa3a3d788530023e0c82d",
				"68daa3cc90a2bb0024b91cf7",
				"68daa3b190a2bb0024b91cce",
				"68daa3b54873af00239e72f8",
				"68daa3c190a2bb0024b91ceb",
				"68daa3d04cbc690025c0dd43"
			]
		},
		"68d745af90a2bb0024b90422": {
			"id": "68d745af90a2bb0024b90422",
			"name": "404",
			"pageUrl": "404"
		},
		"68d745af90a2bb0024b90425": {
			"id": "68d745af90a2bb0024b90425",
			"name": "index",
			"pageUrl": "index",
			"children": []
		},
		"68d745ed4cbc690025c0c304": {
			"id": "68d745ed4cbc690025c0c304",
			"pageUrl": "music",
			"name": "MUSIC"
		},
		"68daa3a3d788530023e0c82d": {
			"id": "68daa3a3d788530023e0c82d",
			"pageUrl": "sports",
			"name": "SPORTS"
		},
		"68daa3add788530023e0c839": {
			"id": "68daa3add788530023e0c839",
			"pageUrl": "portraits",
			"name": "PORTRAITS",
			"styles": {
				"display": "flex",
				"overflow-x": "visible",
				"overflow-y": "visible",
				"width": "100%",
				"height": "auto"
			}
		},
		"68daa3b190a2bb0024b91cce": {
			"id": "68daa3b190a2bb0024b91cce",
			"pageUrl": "film",
			"name": "FILM"
		},
		"68daa3b54873af00239e72f8": {
			"id": "68daa3b54873af00239e72f8",
			"pageUrl": "landscape",
			"name": "LANDSCAPE",
			"children": []
		},
		"68daa3c190a2bb0024b91ceb": {
			"id": "68daa3c190a2bb0024b91ceb",
			"pageUrl": "automotive",
			"name": "AUTOMOTIVE"
		},
		"68daa3cc90a2bb0024b91cf7": {
			"id": "68daa3cc90a2bb0024b91cf7",
			"pageUrl": "bts",
			"name": "BTS"
		},
		"68daa3d04cbc690025c0dd43": {
			"id": "68daa3d04cbc690025c0dd43",
			"pageUrl": "contact",
			"name": "CONTACT"
		}
	},
	"mode": "production",
	"projectType": "gatsby",
	"site": {
		"styles": {
			"background": "#000000",
			"overflow-x": "hidden",
			"width": "100%",
			"height": "auto"
		},
		"seo": {
			"favicon_32px": "https://uploads.quarkly.io/68d745af90a2bb0024b9041d/images/logo.png?v=2025-10-03T14:17:11.831Z",
			"favicon_apple_152px": "",
			"title": "ANDY DOAN | PHOTOGRAPHY",
			"description": "PHOTOGRAPHY PORTFOLIO",
			"og:title": "",
			"customSitemapDomain": "",
			"sitemapFileType": "autogenerated",
			"robotsFileType": "autogenerated"
		}
	}
}